name: bmi_calculator
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  circular_seek_bar: ^1.1.1
  flutter_screenutil: ^5.9.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bloc: ^8.1.4
  bloc: ^8.1.3


flutter:

  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SM
      fonts:
        - asset: fonts/ShabnamMedium.ttf

    - family: SB
      fonts:
        - asset: fonts/ShabnamBold.ttf


